apiVersion: gateway.networking.k8s.io/v1alpha2
kind: BackendLBPolicy
metadata:
  name: lb-policy
spec:
  targetRefs:
  - group: core
    kind: Service
    name: echo-service
  sessionPersistence:
    sessionName: foo-session
    type: Header
