apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echo-service-destinationrule
  namespace: default
spec:
  host: echo-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: session-cookie
          ttl: 30m
