apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-sp-demo2
  namespace: test
spec:
  addresses:
  - value: gateway-sp-demo-istio.default.svc.cluster.local
    type: Hostname
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
    hostname: "example2.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
 name: sp-demo2
 namespace: test
spec:
  parentRefs:
  - name: gateway-sp-demo2
  rules:
  - backendRefs:
    - name: echo-service
      namespace: default
      port: 80
