apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-sp-demo
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sp-demo
spec:
  parentRefs:
  - name: gateway-sp-demo
  rules:
  - backendRefs:
    - name: echo-service
      port: 80
