#!/bin/bash

function perfscale_copy_results() {
  ssh perfscale dnf install -y rsync -q
  rsync --progress -raz --exclude "*results.csv" root@perfscale:/root/e2e-benchmarking/workloads/router-perf-v2/results ~/perf_scale/
}
