#!/bin/bash

function perfscale_copy_results() {
  ssh perfscale dnf install -y rsync -q
  rsync --progress -raz --exclude "*results.csv" root@perfscale:/root/openshift-hacks/perf_scale/results ~/perf_scale/
  rsync --progress -raz --exclude "*results.csv" root@perfscale:/root/openshift-hacks/perf_scale/tests ~/perf_scale/
}
