apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 600
  restartPolicy: Never
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "wget https://github.com/openshift/cluster-ingress-operator.git"]
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        requests:
          memory: "3000Mi"
          cpu: "250m"
