apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1655485953
      service.beta.openshift.io/serving-cert-secret-name: dns-default-metrics-tls
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1655485953
    labels:
      dns.operator.openshift.io/owning-dns: default
    name: dns-hack
    namespace: openshift-dns
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns
      port: 6868
      protocol: UDP
      targetPort: dns
    - name: dns-tcp
      port: 6868
      protocol: TCP
      targetPort: dns-tcp
    - name: metrics
      port: 6869
      protocol: TCP
      targetPort: metrics
    selector:
      dns.operator.openshift.io/daemonset-dns: default
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

