apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: dumper
  name: dumper
  namespace: openshift-dns
spec:
  selector:
    matchLabels:
      app: dumper
  template:
    metadata:
      labels:
        app: dumper
    spec:
      nodeSelector:
        dns: "true"
      containers:
      - command:
        - "/bin/sh"
        - "-c"
        - |
          set -euo pipefail
          tcpdump -s 0 -w /dns.pcap -i any "udp port 53 or tcp port 53 or udp port 5353 or tcp port 5353"
        # oc adm release info --image-for=tools
        image: docker.io/corfr/tcpdump
        name: tcpdump
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host-slash
          readOnly: true
      hostNetwork: true
      nodeSelector:
        "kubernetes.io/os": "linux"
      privileged: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
      volumes:
      - name: host-slash
        hostPath:
          path: /
