apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job
  labels:
    app: curl
spec:
  restartPolicy: Never
  completions: 350
  parallelism: 350
  activeDeadlineSeconds: 100000
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: curl
    spec:
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      initContainers:
      - name: init
        image: quay.io/gspence/curl
        command:
        - "/bin/sh"
        - "-c"
        - |
          set -x
          #nslookup google.com 172.30.0.10 && echo "GOOD" > /wget-dir/index.html || echo "failure"
          #nslookup google.com 172.30.0.10 && echo "GOOD" || echo "failure"
          #wget 172.30.50.73 -O /wget-dir/index.html || exit 0
          #curl -o /wget-dir/index.html -kw "dnslookup: %{time_namelookup} | connect: %{time_connect} | appconnect: %{time_appconnect} | pretransfer: %{time_pretransfer} | starttransfer: %{time_starttransfer} | total: %{time_total} | size: %{size_download}\n" "https://google.com" || exit 0
          #curl -o /wget-dir/index.html -k -H "host: canary-openshift-ingress-canary.apps.gspence-2022-06-13-1020.gcp.devcluster.openshift.com" https://35.227.7.12
          curl -o /wget-dir/index.html -kw "dnslookup: %{time_namelookup} | connect: %{time_connect} | appconnect: %{time_appconnect} | pretransfer: %{time_pretransfer} | starttransfer: %{time_starttransfer} | total: %{time_total} | size: %{size_download}\n" "https://canary-openshift-ingress-canary.${CLUSTER_INGRESS_DOMAIN}/" || exit 0
        volumeMounts:
        - name: wgetdir
          mountPath: "/wget-dir"
        env:
        - name: "CLUSTER_INGRESS_DOMAIN"
          # oc get ingresses.config/cluster -o 'jsonpath={.spec.domain}'
          value: "apps.gspence-2022-06-15-0843.gcp.devcluster.openshift.com"
      containers:
      - name: myservice
        image: quay.io/gspence/busybox
        command: ['sh', '-c', "test -s /wget-dir/index.html; sleep 100000"]
        volumeMounts:
        - name: wgetdir
          mountPath: "/wget-dir"
        readinessProbe:
          exec:
            command:
            - test
            - "-s"
            - /wget-dir/index.html
      volumes:
      - name: wgetdir
        emptyDir: {}
