#!/bin/bash

function oc_ingress_unmanaged_privileged() {
  oc_ingress_unmanaged
  oc_ingress_privileged
}

function oc_ingress_unmanaged_privileged_reset() {
  oc_ingress_managed
  oc_ingress_unprivileged
}

function oc_ingress_managed() {
  oc patch clusterversions/version --type=json --patch='[{"op":"add","path":"/spec/overrides","value":[{"kind":"Deployment","group":"apps/v1","name":"ingress-operator","namespace":"openshift-ingress-operator","unmanaged":false}]}]'
  oc_scale_cvo 1
  oc_ingress_scale_ingress_operator 1
  oc scale --replicas 2 -n openshift-ingress-operator ingresscontroller/default
}

function oc_ingress_unprivileged() {
  oc patch clusterrole/openshift-ingress-router --type=strategic --patch='{"rules":[{"apiGroups":[""],"resources":["endpoints","namespaces","services"],"verbs":["list","watch"]},{"apiGroups":["authentication.k8s.io"],"resources":["tokenreviews"],"verbs":["create"]},{"apiGroups":["authorization.k8s.io"],"resources":["subjectaccessreviews"],"verbs":["create"]},{"apiGroups":["route.openshift.io"],"resources":["routes"],"verbs":["list","watch"]},{"apiGroups":["route.openshift.io"],"resources":["routes/status"],"verbs":["update"]},{"apiGroups":["security.openshift.io"],"resourceNames":["hostnetwork"],"resources":["securitycontextconstraints"],"verbs":["use"]},{"apiGroups":["discovery.k8s.io"],"resources":["endpointslices"],"verbs":["list","watch"]}]}'
  oc patch -n openshift-ingress deployment/router-default --patch='{"spec":{"template":{"spec":{"securityContext":{"runAsUser":null}}}}}'
  oc patch -n openshift-ingress deployment/router-default --patch='{"spec":{"template":{"spec":{"hostNetwork":true}}}}'
}

function oc_ingress_unmanaged() {
  oc_scale_cvo 0
  oc_ingress_scale_ingress_operator 0

  oc patch clusterversions/version --type=json --patch='[{"op":"add","path":"/spec/overrides","value":[{"kind":"Deployment","group":"apps/v1","name":"ingress-operator","namespace":"openshift-ingress-operator","unmanaged":true}]}]'
  oc_ingress_scale_ingress_operator 0
}

function oc_ingress_privileged() {
  oc patch clusterrole/openshift-ingress-router --type=strategic --patch='{"rules":[{"apiGroups":[""],"resources":["endpoints","namespaces","services"],"verbs":["list","watch"]},{"apiGroups":["authentication.k8s.io"],"resources":["tokenreviews"],"verbs":["create"]},{"apiGroups":["authorization.k8s.io"],"resources":["subjectaccessreviews"],"verbs":["create"]},{"apiGroups":["route.openshift.io"],"resources":["routes"],"verbs":["list","watch"]},{"apiGroups":["route.openshift.io"],"resources":["routes/status"],"verbs":["update"]},{"apiGroups":["security.openshift.io"],"resourceNames":["privileged"],"resources":["securitycontextconstraints"],"verbs":["use"]},{"apiGroups":["discovery.k8s.io"],"resources":["endpointslices"],"verbs":["list","watch"]}]}'
  oc patch -n openshift-ingress deployment/router-default --patch='{"spec":{"template":{"spec":{"securityContext":{"runAsUser":0}}}}}'
}

function oc_scale_cvo() {
  if [[ $? == "" ]]; then
    echo "ERROR: you need to provide replicas"
    return 1
  fi
  oc scale --replicas $1 -n openshift-cluster-version deployments/cluster-version-operator
}

function oc_ingress_scale_router_default() {
  if [[ $1 = "" ]]; then
    echo "ERROR: You need to provide a scale #"
    return 1
  fi
  oc scale --replicas=$1 -n openshift-ingress deployment/router-default
}

function oc_ingress_scale_ingress_operator() {
  if [[ $1 = "" ]]; then
    echo "ERROR: You need to provide a scale #"
    return 1
  fi
  oc scale --replicas $1 -n openshift-ingress-operator deployments ingress-operator
}

function oc_ingress_rsh_only_router() {
  if [[ "$1" == "" ]]; then
    router="default"
  else
    router="$1"
  fi

  if [[ $(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running |  wc -l) -ne 1 ]]; then
    echo "ERROR: There are either 0 or more than 1 ${router} routers running"
    oc get pods -n openshift-ingress
    return 1
  fi

  oc rsh -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running | head -1 | awk '{print $1}')
}

function oc_ingress_rsh_any_router() {
  if [[ "$1" == "" ]]; then
    router="default"
  else
    router="$1"
  fi
  oc rsh -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running | head -1 | awk '{print $1}')
}

function oc_ingress_exec_any_router() {
  router="$1"
  shift 1
  oc exec -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running | head -1 | awk '{print $1}') $@
}

function oc_ingress_cp_into_only_router_default() {
  if [[ $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running |  wc -l) -ne 1 ]]; then
    echo "ERROR: There are either 0 or more than 1 default routers running"
    oc get pods -n openshift-ingress
    return 1
  fi

  oc cp -n openshift-ingress $1 $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running | head -1 | awk '{print $1}'):${2}
}

function oc_ingress_cp_out_any_router_default() {
  oc cp -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running | head -1 | awk '{print $1}'):${1} $(basename ${1})
}

function oc_ingress_haproxy_debug_router_default() {
  if [[ $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running |  wc -l) -ne 1 ]]; then
    echo "ERROR: There are either 0 or more than 1 default routers running"
    oc get pods -n openshift-ingress
    return 1
  fi

  oc exec -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running | head -1 | awk '{print $1}') -- bash -c "killall haproxy; pkill haproxy; haproxy -f /var/lib/haproxy/conf/haproxy.config -V -d"
}


function oc_ingress_get_router_pods() {
  oc get pods -n openshift-ingress $@
}


function oc_ingress_get_router_deployments() {
  oc get deployments -n openshift-ingress $@
}

function oc_ingress_get_ingress_operator() {
  oc get pods -n openshift-ingress-operator $@
}

function oc_ingress_get_ingress_controllers() {
  oc get -n openshift-ingress-operator ingresscontrollers $@
}

function oc_ingress_logs_ingress_operator() {
  oc logs -n openshift-ingress-operator $(oc get -n openshift-ingress-operator pods --no-headers | head -1 | awk '{print $1}') -c ingress-operator $@
}

function oc_ingress_enable_http2_router_default() {
  oc -n openshift-ingress-operator annotate ingresscontrollers/default ingress.operator.openshift.io/default-enable-http2=true
}

function oc_ingress_edit_ingresscontroller() {
  if [[ "$1" == "" ]]; then
    IC="default"
  else
    IC="$1"
  fi

  oc edit -n openshift-ingress-operator ingresscontrollers/${IC}
}

function oc_ingress_edit_router_deployment() {
  if [[ "$1" == "" ]]; then
    IC="default"
  else
    IC="$1"
  fi

  oc edit -n openshift-ingress deployments/router-${IC}
}

function oc_ingress_edit_ingress_operator_deployment() {
  oc edit deployment -n openshift-ingress-operator ingress-operator
}

function oc_ingress_delete_ingresscontroller() {
  if [[ "$1" == "" ]]; then
    echo "ERROR: You need to provide an ingress controller name"
    return 1
  fi

  oc delete -n openshift-ingress-operator ingresscontroller $@
}

function oc_ingress_logs_any_router_default_access() {
  oc logs -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-default" | grep Running | head -1 | awk '{print $1}') -c logs --follow $@
}

function oc_ingress_logs_any_router() {
  if [[ "$1" == "" ]]; then
    router="default"
  else
    router="$1"
  fi
  shift 1
  
  oc logs -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running | head -1 | awk '{print $1}') --follow $@
}


function oc_ingress_logs_any_router_wait_appear() {
  if [[ "$1" == "" ]]; then
    router="default"
  else
    router="$1"
  fi
  shift 1
  
  while true; do
    pod=$(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running | head -1 | awk '{print $1}')
    if [[ "$pod" != "" ]]; then
      oc logs -n openshift-ingress $(oc get pods -n openshift-ingress --no-headers | grep "^router-${router}" | grep Running | head -1 | awk '{print $1}') --follow $@
    else
      echo -n "."
    fi
  done
}

function oc_ingress_run_logging_openshift_router() {
  oc -n openshift-ingress rsh -c router deploy/router-default sh -c 'rm -rf /tmp/haproxy && mkdir -p /tmp/haproxy/{router/{certs,cacerts,whitelists},{conf/.tmp,run,bin,log}} && /bin/openshift-router --v=10 --template=/var/lib/haproxy/conf/haproxy-config.template --reload=/bin/true --update-status=false --stats-port=1937 --metrics-type=haproxy --working-dir=/tmp/haproxy'
}

function oc_ingress_get_router_image() {
  oc_ingress_get_router_deployments router-default -o json | jq -r '.spec.template.spec.containers[0].image'
}

function oc_ingress_enable_verbose_openshift_router() {
  echo "Log in to quay.io"
  podman login quay.io || return 1
  image=$(oc_ingress_get_router_image)
  podman pull --authfile /home/gspence/.secrets/pull-secret.txt $image || return 1
  sha=$(echo "$image" |  awk -F":" '{print $2}')
  tag_new="quay.io/gspence/openshift-router:${sha}"
  podman build -t $tag_new  -<<EOF
FROM $image
ENTRYPOINT ["/usr/bin/openshift-router","--v=10"]
EOF
  if [[ $? -ne 0 ]]; then
    echo "ERROR: Build failed"
    return 1
  fi
  podman push $tag_new || return 1
  oc_ingress_patch_router_image $tag_new || return 1
}

function oc_ingress_patch_router_image() {
  if [[ "$1" == "" ]]; then
    echo "ERROR: You need to provide an image"
    return 1
  fi
  oc scale --replicas 0 -n openshift-cluster-version deployments/cluster-version-operator
  oc -n openshift-ingress-operator patch deploy/ingress-operator --type=strategic --patch='{"spec":{"template":{"spec":{"containers":[{"name":"ingress-operator","env":[{"name":"IMAGE","value":"'${1}'"}]}]}}}}'
}

function oc_ingress_force_delete_terminating_router_pods() {
  for i in $(oc get pods -n openshift-ingress --no-headers | grep Terminating | awk '{print $1}'); do
    oc delete -n openshift-ingress pod $i --force
  done
}

function oc_ingress_maxconn_auto() {
  oc -n openshift-ingress-operator patch ingresscontroller/default --type=merge --patch='{"spec":{"tuningOptions":{"maxConnections":-1}}}'
  oc -n openshift-ingress-operator patch ingresscontroller/default --type=merge --patch='{"spec":{"unsupportedConfigOverrides":{"maxConnections":-1}}}'
}

function oc_ingress_patch_ingresscontroller_routeselector() {
  if [[ "$1" == "" ]]; then
    oc -n openshift-ingress-operator patch ingresscontroller/default --type=merge --patch='{"spec":{"routeSelector":{"matchLabels":{"type":null}}}}'
  else
    oc -n openshift-ingress-operator patch ingresscontroller/default --type=merge --patch='{"spec":{"routeSelector":{"matchLabels":{"type":"'$1'"}}}}'
  fi
}

function oc_ingress_rollout_router() {
  if [[ "$1" == "" ]]; then
    router="default"
  else
    router="$1"
  fi
  shift 1

  oc rollout restart deployment -n openshift-ingress router-${router}
}

alias oc_update_pull_secrets="oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=/home/gspence/.secrets/pull-secret.txt"
alias oc_get_pull_secrets="oc get secret/pull-secret -n openshift-config --template='{{index .data \".dockerconfigjson\" | base64decode}}'"
alias oc_get_console_url="oc get routes -n openshift-console console -o go-template='{{.spec.host}}{{\"\n\"}}'"

function oc_open_console() {
  URL=$(oc_get_console_url)
  xdg-open https://${URL}
}

function oc_curl() {
  oc run curl-pod --image=radial/busyboxplus:curl -i --tty --rm
}

function oc_ingress_istioapi_logs() {
  oc logs -f $(oc get -n istio-system pod --no-headers | grep istio-ingressgateway | awk '{print $1}') -n istio-system
}

function oc_ingress_gwapi_logs() {
  oc logs -f $(oc get -n gwapi pod --no-headers | grep "gateway-" | awk '{print $1}') -n gwapi
}

function oc_ingress_domain() {
  oc get ingresses.config/cluster -o jsonpath={.spec.domain}
  echo
}

function oc_logs() {
  if [[ "$1" == "" ]]; then
    echo "ERROR: You need to provide a pod name"
    return 1
  fi
  if [[ "$1" == "-n" ]]; then
    NS="-n $2"
    shift 2
  else
    NS="-A"
  fi
  for pod in $(oc get pods $NS --no-headers | grep "${1}-" | awk '{print $2}'); do
    echo "${pod}:"
    oc logs $pod --timestamps
  done
}
