apiVersion: v1
kind: Service
metadata:
  name: router-service1
  labels:
    app: router-service1
spec:
  selector:
    app: router-service1
  ports:
    - port: 8676
      name: router-service1
      protocol: TCP

