apiVersion: v1
data:
  Corefile: |
    com:5353 net:5353 org:5353 {
        log
        forward . 172.20.50.7
    }
    .:5353 {
        log
        errors
        health
        prometheus :9153
        forward . 172.30.0.10
        cache 30
        reload
    }
    com:5354 net:5354 org:5354 {
        log
        forward . 172.20.50.7
    }
    .:5354 {
        log
        errors
        health
        prometheus :9153
        forward . 172.30.0.10
        cache 30
        reload
    }
kind: ConfigMap
metadata:
  name: spk-coredns-cm
  namespace: spk-coredns
  selfLink: /api/v1/namespaces/spk-coredns/configmaps/spk-coredns-cm
