# Needs to be updated later...being lazy
FROM quay.io/amcdermo/openshift-router-ocpbugs-10003:2.6.9

USER 0
COPY *.rpm /

RUN rpm -e haproxy26
RUN rpm -Uvh /*.rpm

RUN setcap 'cap_net_bind_service=ep' /usr/sbin/haproxy && \
    chown -R :0 /var/lib/haproxy && \
    chmod -R g+w /var/lib/haproxy && \
    chmod +x /usr/sbin/haproxy

WORKDIR /var/lib/haproxy/conf
USER 1001
EXPOSE 80 443
