apiVersion: apps/v1
kind: Deployment
metadata:
  name: segfault
  namespace: openshift-ingress
  labels:
    app: segfault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segfault
  template:
    metadata:
      labels:
        app: segfault
    spec:
      containers:
      - name: segfault
        image: quay.io/icdh/segfaulter
        args: ["sleep","90000"]
        securityContext:
          privileged: true
          runAsUser: 0
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 0
      privileged: true
