FROM registry.access.redhat.com/ubi8/ubi:latest

RUN ls -l /etc/yum.repos.d/
RUN dnf install -y gcc gdb make openssl-devel pcre-devel zlib-devel diffutils sudo less vim wget strace lsof curl rsyslog procps-ng util-linux socat git
