#!/bin/bash

#if [[ "$(find ~/.secrets/pull-secret.txt -mmin +18720)" != "" ]]; then
#  echo "WARNING: ~/.secrets/pull-secret.txt hasn't been touched in 13 days. Re-login into the CI registry"
#  echo "    1. Visit https://console.redhat.com/openshift/install/pull-secret and download pull-secret"
#  echo "    2. cp ~/Downloads/pull-secret to ~/.secrets/pull-secret.txt"
#  echo "    3. Visit https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com/"
#  echo "    4. Log in -> Copy login command -> unset KUBECONFIG -> Use login command"
#  echo "    5. oc registry login --to=/home/$USER/.secrets/pull-secret.txt"
#  echo "    6. Test via:"
#  echo "       podman pull --authfile ~/.secrets/pull-secret.txt registry.ci.openshift.org/ocp/4.12:base"
#fi

function ci_delete_cluster() {
  ~/clusters/cluster-installer.sh delete "$1"
}

function ci_launch_latest_aws() {
  ~/clusters/cluster-installer.sh create "$(find ~/clusters/4.* -maxdepth 0 -type d | sort --version-sort | tail -1)" aws
}

function ci_launch_latest_gcp() {
  ~/clusters/cluster-installer.sh create "$(find ~/clusters/4.* -maxdepth 0 -type d | sort --version-sort | tail -1)" gcp
}

function ci_cleanup_all_clusters() {
  for cluster in $(find ~/clusters -iname "metadata.json"); do
      kubeconfig=$(dirname ${cluster})/auth/kubeconfig;
      cluster_dir=$(dirname $cluster)
      if [[ ! -f "${cluster_dir}/building" ]]; then
        ci_delete_cluster $cluster_dir
      else
        echo "$cluster_dir is being built"
      fi
  done
}

function ci_cleanup_old_clusters() {
  for cluster in $(find ~/clusters -iname "metadata.json"); do
      kubeconfig=$(dirname ${cluster})/auth/kubeconfig;
      cluster_dir=$(dirname $cluster)
      if [[ -f "${kubeconfig}" ]]; then
        if [[ ! -f "${cluster_dir}/building" ]]; then
          KUBECONFIG=${kubeconfig} oc version &> /dev/null
          if [[ $? -ne 0 ]]; then
            echo "$cluster_dir is dead. Cleaning up."
            ci_delete_cluster $cluster_dir
	  else
	    echo "$cluster_dir is alive."
	  fi
	else
	  echo "$cluster_dir is being built"
	fi
      else
        echo "${kubeconfig} doesn't exit. Cleaning up."
	ci_delete_cluster $cluster_dir
      fi

  done
}

function ci_findactiveclusters() {
  for cluster in $(find ~/clusters -iname "metadata.json"); do
    kubeconfig=$(dirname ${cluster})/auth/kubeconfig
    if [[ -f "${kubeconfig}" ]]; then
      echo "export KUBECONFIG=${kubeconfig}"
    else
      echo "ERROR: ${kubeconfig} doesn't exit"
    fi
  done
}

function ci_kubeconfiglastestcluster() {
  latestCluster=$(dirname $(find ~/clusters -iname "metadata.json" | sort -h  | tail -n1))
  echo "+ export KUBECONFIG=${latestCluster}/auth/kubeconfig"
  export KUBECONFIG=${latestCluster}/auth/kubeconfig
}
