---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1580391904
      service.beta.openshift.io/serving-cert-secret-name: dns-default-metrics-tls
      service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1580391904
    creationTimestamp: "2020-01-30T13:46:08Z"
    labels:
      dns.operator.openshift.io/owning-dns: default
    name: dns-default
    namespace: openshift-dns
    ownerReferences:
    - apiVersion: operator.openshift.io/v1
      controller: true
      kind: DNS
      name: default
      uid: d8bbcd7a-f7a5-4612-ae86-d6e8d620756b
    resourceVersion: "3123306608"
    uid: 372865de-65f6-4d06-8ba4-4a964799e0ac
  spec:
    clusterIP: 172.30.0.10
    clusterIPs:
    - 172.30.0.10
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: dns
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: metrics
      port: 9154
      protocol: TCP
      targetPort: metrics
    selector:
      dns.operator.openshift.io/daemonset-dns: default
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: ServiceList
metadata:
  resourceVersion: "3290959246"
