apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: nlb-test
  spec:
    replicas: 1
    selector:
      app: nlb-test
      deploymentconfig: nlb-test
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: nlb-test
          deploymentconfig: nlb-test
      spec:
        #nodeName: ip-10-0-156-113.ec2.internal
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          name: nlb-test
          command:
            - /usr/bin/socat
            - TCP4-LISTEN:8676,reuseaddr,fork
            - EXEC:'/bin/bash -c \"printf \\\"HTTP/1.0 200 OK\r\n\r\n\\\"; sed -e \\\"/^\r/q\\\"\"'
          ports:
          - containerPort: 8676
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: nlb-test
    labels:
      app: nlb-test
  spec:
    selector:
      app: nlb-test
    ports:
      - port: 8676
        name: nlb-test
        protocol: TCP
