apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-port-redirect
  namespace: gwapi
spec:
  parentRefs:
  - name: gateway
    namespace: gwapi
  hostnames: ["http-port-redirect.hf.${GWAPI_DOMAIN}"]
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: http
        port: 8000
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-hsts
  namespace: gwapi
spec:
  parentRefs:
  - name: gateway
    namespace: gwapi
  hostnames: ["http-hsts.hf.${GWAPI_DOMAIN}"]
  rules:
  - backendRefs:
    - name: nginx
      port: 8000
  - filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: "Strict-Transport-Security"
          value: "max-age=99999;includeSubDomains;preload"

