apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: echo-deployment
    labels:
      app: echo
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: echo
    template:
      metadata:
        labels:
          app: echo
      spec:
        containers:
        - name: echo-container
          image: nginx
          ports:
          - containerPort: 80
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "echo \"Hello from $(hostname)\" > /usr/share/nginx/html/index.html"]
- apiVersion: v1
  kind: Service
  metadata:
    name: router-service1
    labels:
      app: router-service1
  spec:
    selector:
      app: echo
    ports:
      - port: 80
        name: echo
        protocol: TCP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: router-service1
  spec:
    to:
      kind: Service
      name: router-service1
      weight: 10
