apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: router-service1
  spec:
    replicas: 1
    selector:
      app: router-service1
      deploymentconfig: router-service1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: router-service1
          deploymentconfig: router-service1
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          name: router-service1
          command:
            - /usr/bin/socat
            - TCP4-LISTEN:8676,reuseaddr,fork
            - EXEC:'/bin/bash -c \"printf \\\"HTTP/1.0 200 OK\\\nset-cookie:X=Y\\\nset-cookie:P=Q\r\n\r\n\\\"; sed -e \\\"/^\r/q\\\"\"'
          ports:
          - containerPort: 8676
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: router-service1
    labels:
      app: router-service1
  spec:
    selector:
      app: router-service1
    ports:
      - port: 8676
        name: router-service1
        protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    name: router-service1
  spec:
    to:
      kind: Service
      name: router-service1
      weight: 10
    tls:
      termination: passthrough
