apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: loadbalancer
    namespace: openshift-ingress-operator
  spec:
    domain: scope.gspence-2022-10-13-1354.devcluster.openshift.com
    endpointPublishingStrategy:
      type: LoadBalancerService
      loadBalancer:
        DNSManagementPolicy: Managed
        scope: External
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
