apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper-deploy
  labels:
    app: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: sleeper
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ba44dead03ea74107f90d58525106fb52d27a120b73c6cc8e2be31d37043ca1c
        command:
        - "/bin/sh"
        - "-c"
        - |
          set -x
          sleep 100000
