apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: grant-1
    type: public
  name: grant-1-insecure
spec:
  host: grant.apps.gspence-2022-01-27-1635.gcp.devcluster.openshift.com
  to:
    kind: Service
    name: django-psql-example
    weight: 100
  wildcardPolicy: None
  #alternateBackends:
  #- kind: Service
  #  name: mysql
  #  weight: 10
