apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    release.openshift.io/create-only="true"
  name: admin-acks
  namespace: openshift-config
data:
    ack-4.8-kube-122-api-removals-in-4.9: "true"
